### PR TITLE
Removed lines of code that are making people freak up in this moment

### PR DESCRIPTION
**Pull request by TechAle**
People think this is a rat
i dunno if it is or not, imma just remove this so that everyone are happy

### CODE REVIEW

**Comment by DriftyDev** [comment]
literaly its just nbt data

**Comment by HausemasterIssue** [comment]
why the fuck is that array so long? are they writing an essay or something?

**Comment by OlDestiny** [comment]
the byte array is almost like renorat but shorter.

**Comment by ToxicAven** [comment]
> the byte array is almost like renorat but shorter.

Its probably not a rat, but people freaking out since it looks a ton like renosense's rat, yeah

**Comment by threevt** [comment]
> why the fuck is that array so long? are they writing an essay or something?

loads a full kit in https://media.discordapp.net/attachments/917804928230113320/917805851123798106/2021-12-07_07.52.36.png?width=1275&height=682

**Comment by BotDebug** [comment]
Close this meme issue pls

**Comment by OldChunks** [comment]
> > the byte array is almost like renorat but shorter.
> 
> Its probably not a rat, but people freaking out since it looks a ton like renosense's rat, yeah

its literally kit

**Comment by TechAle** [comment]
[message_1.txt](https://github.com/Gopro336/3arthh4ck_1.3.1-BUILDABLE-SRC/files/7669920/message_1.txt)
Insane rat

**Comment by HausemasterIssue** [comment]
theoretically those words could be code words for numbers or shit, but nahhhh these people don't have the iq nor time nor effort to do that

**Comment by master7720** [comment]
its not a rat....

**Comment by Gopro336** [comment]
I think its better to leave this in, to retain client functionality.

**Pull request closed without merging**
